---
# tasks file for common secrets
- name: Set tracking/search shared secret
  set_fact:
    reposearch_shared_secret: "{{ hostvars.localhost.reposearch_shared_secret }}"
  when: inventory_hostname in groups.repository + groups.search

- name: Set repo_db_password secret
  set_fact:
    repo_db_password: "{{ hostvars.localhost.repo_db_password }}"
  when: inventory_hostname in groups.repository + groups.database

- name: Set sync_db_password secret
  set_fact:
    sync_db_password: "{{ hostvars.localhost.sync_db_password }}"
  when: inventory_hostname in groups.syncservice + groups.database
