- hosts: all
  gather_facts: false
  tasks:
    - name: Include secrets file
      include_vars:
        file: ../secrets.yml
    - name: Ensure that all secrets are set
      assert:
        that:
          - repo_db_password is defined and repo_db_password | length > 0
          - sync_db_password is defined and sync_db_password | length > 0
        msg: "Secrets must be provided in secrets.yml before running the playbook"
        quiet: true